### ISSUE TITLE
关于Yelp数据集处理数据不一致的问题

### ISSUE THREAD

**Issue by Goooooooooooooooogle** [aHuiWang/CIKM2020-S3Rec#14]
`Yelp Raw data has been processed! Lower than 0.0 are deleted!
User 5-core complete! Item 5-core complete!
Total User: 19855, Avg User: 10.4279, Min Len: 5, Max Len: 235
Total Item: 14541, Avg Item: 14.2387, Min Inter: 5, Max Inter: 317
Iteraction Num: 207045, Sparsity: 99.93%
Begin extracting meta infos...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150346/150346 [00:49<00:00, 3008.29it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14541/14541 [00:00<00:00, 491683.26it/s]
before delete, attribute num:809
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14541/14541 [00:00<00:00, 136748.70it/s]
after delete, attribute num:809
attributes len, Min:1, Max:36, Avg.:5.2599
Yelp & 19,855& 14,541 & 10.4& 14.2& 207,045& 99.93\%&809&5.3 \`

我用了/data/data_process.py 程序处理官网下载的数据集【https://www.yelp.com/dataset】然后使用里面的yelp_academic_dataset_review.json， yelp_academic_dataset_business.json 文件， 但是结果如上图所示。

论文的Yelp数据是
Yelp
users: 30,431
items: 20,033
avg.: 10.4
actions: 316,354

请问是数据集的问题吗？还是时间需要调整？
`def main(data_name, data_type='Amazon'):
    assert data_type in {'Amazon', 'Yelp'}
    np.random.seed(12345)
    rating_score = 0.0  # rating score smaller than this score would be deleted
    # user 5-core item 5-core
    user_core = 5
    item_core = 5
    attribute_core = 0

    if data_type == 'Yelp':
        date_max = '2019-12-31 00:00:00'
        date_min = '2019-01-01 00:00:00'
        datas = Yelp(date_min, date_max, rating_score)
    else:
        datas = Amazon(data_name+'_5', rating_score=rating_score)`

**Comment by aHuiWang** [comment]
https://github.com/aHuiWang/CIKM2020-S3Rec/issues/8

**Comment by Goooooooooooooooogle** [comment]
感谢!
