### ISSUE TITLE
About "attribute_file = './data_path/artist2attributes.json'"

### ISSUE THREAD

**Issue by dongjingWANG** [aHuiWang/CIKM2020-S3Rec#3]
Hi, thank you very much for sharing the code. May I ask where to find "artist2attributes.json" file in the "data_preprocess.py"?

**Comment by aHuiWang** [comment]
I'm sorry for this typo and delay reply.
It is the '2k/artist2tags.json' in the raw LastFM dataset.

**Comment by dongjingWANG** [comment]
Thank you very much
