### ISSUE TITLE
About Beauty datasets

### ISSUE THREAD

**Issue by codewithzichao** [aHuiWang/CIKM2020-S3Rec#5]
Hi, thanks for your great work!
But I have a question. Did you use the smaller dataset mentioned in http://jmcauley.ucsd.edu/data/amazon/links.html, or did you contact the author to obtain a larger one?  In other word, if i run your code for reproduction, do I need to download datasets from other website? Or are all datasets in your repo?
Thanks

**Comment by aHuiWang** [comment]
We use the smaller dataset (5-core) mentioned in http://jmcauley.ucsd.edu/data/amazon/links.html.  We preprocessed the raw dataset and got the files in the *data* directory. If you just to reproduce the results, you can directly run the code.
