### ISSUE TITLE
About GPUs

### ISSUE THREAD

**Issue by codewithzichao** [aHuiWang/CIKM2020-S3Rec#6]
thanks for your work! I have reproduced your work recently. But it is suppppper time-consuming. What kind of GPU did you use at the time, how many GPUs did you use and how long did it take for the pre-training phase and the fine-tuning phase? 😭

**Comment by aHuiWang** [comment]
> 

1 Titan Xp GPU with 12G mem. For Beauty dataset, it take about 3 minutes for a pretrain epoch and 20 seconds for a finetune epoch. Sports may take a longer time(about 9min / 50s )

**Comment by codewithzichao** [comment]
many thanks!
