### ISSUE TITLE
Could you provide the code of other models that you reproduced? Thanks

### ISSUE THREAD

**Issue by gtx30** [aHuiWang/CIKM2020-S3Rec#7]
Hi, 
I am a beginner in recommendation system and have recently been working on sequence recommendations. Thank you very much for providing the code for the s3rec model, I have reproduced the results, which I learned a lot from.
 
But I encountered a problem. I noticed that the gru4rec, SASrec, bert4rec, and caser models have very different values in different paper, but I have insufficient code ability to find difficulties in reproducing these models. I was so frustrated😭. Could you provide the code of these models  you reproduced?  Thanks! 😭

**Comment by aHuiWang** [comment]
I implemented some of them in RecBole. You can refer to this library (https://github.com/RUCAIBox/RecBole). In addition, different experimental settings and training methods (such as loss function) could bring different results. So you can also carefully check.

**Comment by gtx30** [comment]
thanks.
