### ISSUE TITLE
About the processing of yelp datasets.

### ISSUE THREAD

**Issue by gtx30** [aHuiWang/CIKM2020-S3Rec#8]
Thanks for your great work! But i encounted two questions.

1. There is a question which is about metric calculation puzzled me when i read your code about s3rec.  [get_sample_scores](https://github.com/aHuiWang/CIKM2020-S3Rec/blob/master/trainers.py#L53), this is the position of code. Could you explain meaning of this line of code? 
<img width="696" alt="截屏2022-01-11 下午7 48 19" src="https://user-images.githubusercontent.com/96908711/148937578-0a017fe6-3d4f-418d-827b-36a9f56ca781.png">

2. when i use your code named data_process.py to handle the yelp dataset that is downloaded from https://www.yelp.com/dataset, i got the results as follow , which is different from  the results of your paper. So am i doing something wrong？
<img width="568" alt="截屏2022-01-12 上午1 59 41" src="https://user-images.githubusercontent.com/96908711/148996580-e957d983-57e2-40d6-a7f1-e12c22382636.png">

<img width="581" alt="截屏2022-01-12 上午2 02 48" src="https://user-images.githubusercontent.com/96908711/148997019-95a4d5de-7d81-4474-b0f8-7cadbe7e281b.png">

many thanks.

**Comment by aHuiWang** [comment]
1. Note that i put the ground truth at the first position and i use argsort twice to get its rank. You can check argsort for detail.
![截屏2022-01-13 下午3 36 29](https://user-images.githubusercontent.com/42857066/149286125-7f2f4dc4-3f7f-4b80-8e47-f7ff04563919.png)

2. The size of yelp_academic_dataset_review.json is 6325565224B. I wonder if it's because the downloaded version is different.

**Comment by gtx30** [comment]
> 1. Note that i put the ground truth at the first position and i use argsort twice to get its rank. You can check argsort for detail.
>    ![截屏2022-01-13 下午3 36 29](https://user-images.githubusercontent.com/42857066/149286125-7f2f4dc4-3f7f-4b80-8e47-f7ff04563919.png)
> 2. The size of yelp_academic_dataset_review.json is 6325565224B. I wonder if it's because the downloaded version is different.

Thanks for your reply!  You are right, it is true that the version of the yelp dataset is different. I found  another version of yelp dataset that matches what you said, it's same as the result of your paper.

<img width="559" alt="截屏2022-01-13 下午4 15 42" src="https://user-images.githubusercontent.com/96908711/149291662-2b23d885-1945-458c-8bf1-08e184317d7c.png">
 
Thanks for your patience, have a nice day~

**Comment by AnHongjun** [comment]
Hello, I encountered the same problem as you when dealing with yelp, but I didn't find any other version on the official website (https://www.yelp.com/dataset,), only this one json, I really don't know where to download other versions from, can you tell me how you found it?
![屏幕截图 2022-04-26 160917](https://user-images.githubusercontent.com/20458518/165254188-d4f4ea8a-9c48-4f64-bb8d-19b11b8e8fe7.png)
![c9b47a4c85757d377010d897d21a097](https://user-images.githubusercontent.com/20458518/165254399-5ced2a11-8468-4096-a7ec-5ebfe695d9b3.png)

**Comment by Goooooooooooooooogle** [comment]
Can you provide a way to download this Yelp dataset(6325565224B)? I've been looking here for a long time, but I can't find it. This has been bothering me for a long time. Thank you so much!
